blog/apis/urls.py
from django.urls import path
from rest_framework.documentation import include_docs_urls

from .account_views import (RegisterationView, LoginView)
from .blog_views import (
    HomeView,
    CreateBlogView,
    PostListView,
    PostDetailView,
    PostApprovalListView,
    PostApprovalFormView,
    CommentView,
    ReplyView,
    NotificationView,
)


post_detail = PostDetailView.as_view({
    'get': 'retrieve',
    'put': 'update',
    'delete': 'destroy'

})
post_list = PostListView.as_view({'get': 'list'})
post_approval_list = PostApprovalListView.as_view({'get': 'list'})

post_approve = PostApprovalFormView.as_view({'put': 'update'})
notification = NotificationView.as_view({
    'get': 'list',
    'put': 'update'
})

urlpatterns = [
    path('docs', include_docs_urls(
        title='Blogs API Docs'
    )),
    path('register', RegisterationView.as_view({'post': 'create'}), name='api-register'),
    path('login', LoginView.as_view({'post': 'create'}), name='api-login'),

    path('blogs', HomeView.as_view({'get': 'list'}), name='api-home'),
    path('create-blog', CreateBlogView.as_view({'post': 'create'}), name='api-create-blog'),
    path('myblog', post_list, name='api-myblog'),
    path(
        'blog/<int:pk>',
        post_detail,
        name='api-blog-operation'
    ),
    path('approval-list', post_approval_list, name='api-approval-list'),
    path('approve/<int:pk>', post_approve, name='api-approve'),

    path('comment', CommentView.as_view({'post': 'create'}), name='api-comment'),
    path('reply', ReplyView.as_view({'post': 'create'}), name='api-reply'),
    path('notification', notification, name='api-notification'),
]

blog/urls.py
from django.views.generic import TemplateView
from django.urls import path, include
from django.conf.urls import url
from .views import *


urlpatterns = [
    path('api/', include('blog.apis.urls')),
    path(
        'login',
        CustomLoginView.as_view(),
        name='login'
    ),
    path(
        'post',
        IndexView.as_view(),
        name='post'
    ),
    path(
        'post_list',
        PostListView.as_view(),
        name='post_list'
    ),
    path(
        'post/<int:pk>',
        PostDetailView.as_view(),
        name='post_detail'
    ),
    path(
        'post/<int:pk>/update',
        PostUpdateView.as_view(),
        name='post_update'
    ),
    path(
        '',
        HomeView.as_view(),
        name="home"
    ),
    path(
        'post-approve/<int:pk>',
        PostApprovalView.as_view(),
        name='post_approve'
    ),
    path(
        'post/approve-list',
        PostApprovalListView.as_view(),
        name="post_approve_list"
    ),
    path(
        'post/<int:pk>/delete',
        PostDeleteView.as_view(),
        name="post_delete"
    ),
    url(
        r'post/comment/(?P<pk>[0-9]+)$',
        CommentReplyView.as_view(),
        name="comment_reply"
    ),
    path(
        'post/approved-list/',
        PostApprovedView.as_view(),
        name="user_approved"
    ),
    # path(
    #     'user-info/',
    #     UserInfoView.as_view(),
    #     name="user_info"
    # ),
    # url(
    #     r'user-detail/(?P<slug>[\w.@+-]+)/$',
    #     UserDetailView.as_view(),
    #     name="user_detail"
    # ),
    # path(
    #     'greeting/',
    #     TemplateView.as_view(template_name="blog/greeting.html"),
    #     name='greeting'
    # ),
]

multiuser_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache

from ckeditor_uploader import views as uploader_views

from blog import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('django.contrib.auth.urls')),
    path(
        'blog/signup/editor/',
        views.EditorSignUpView.as_view(),
        name='editor_signup'
    ),
    path(
        'blog/signup/chief/',
        views.ChiefSignUpView.as_view(),
        name='chief_signup'
    ),
    path('', include('blog.urls')),
    path('user/', include('accounts.urls')),
    path('notify/', include('notifications.urls')),
    url(r'^ckeditor/upload/',
        uploader_views.upload, name='ckeditor_upload'),
    url(r'^ckeditor/browse/',
        never_cache(uploader_views.browse), name='ckeditor_browse'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG and settings.FLAG:
    import debug_toolbar
    urlpatterns += [path('debug', include(debug_toolbar.urls))]
    urlpatterns += [url(r'^media/(?P<path>.* )$', serve,
                        {'document_root': settings.MEDIA_ROOT})]
    # urlpatterns += static('media/', document_root=settings.MEDIA_ROOT)

blog/models.py
import datetime
from django.contrib.auth.models import AbstractUser
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField


REQUEST_CHOICES = (
    ('api', 'api'),
    ('template', 'template')
)
DEGREE = (
    ('metric', 'Metriculate'),
    ('inter', 'Intermediate'),
    ('grad', 'Graduation'),
    ('pg', 'Post-Graduation'),
    ('dr', 'doctorate'),
)
YEAR_CHOICES = [(r, r) for r in range(1950, datetime.date.today().year + 5)]
RATING_CHOICES = [(r, r) for r in range(0, 101)]


class User(AbstractUser):
    is_editor = models.BooleanField(default=False)
    is_chief = models.BooleanField(default=False)


class Post(models.Model):
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    title = models.CharField(max_length=255)
    text = RichTextUploadingField()
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(auto_now_add=True)
    is_approve = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    request_from = models.CharField(
        max_length=10,
        choices=REQUEST_CHOICES,
        default='template'
    )

    def __str__(self):
        return self.title

    def delete(self):
        self.is_deleted = True
        self.save()

    def save(self, *args, **kwargs):
        self.full_clean()  # performs regular validation then clean()
        super(Post, self).save(*args, **kwargs)

    def clean(self):
        self.text = self.text.strip()

    class Meta:
        ordering = ["-created_date"]


class Editor(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True
    )

    def __str__(self):
        return self.user


class Comment(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comment'
    )
    blog = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    comment_datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_datetime']


class Reply(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='reply'
    )
    blog = models.ForeignKey(Post, on_delete=models.CASCADE)
    which_comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    reply = models.TextField()
    reply_datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-reply_datetime']

blog/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
)
from django.views.generic.edit import FormMixin, FormView
from django.urls import reverse_lazy
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.conf import settings

from .decorators import editor_required, chief_required
from .forms import *
from .models import *
from notifications.signals import send, recieve


class HomeView(ListView):
    template_name = 'blog/view_post.html'
    model = Post
    paginate_by = 10

    def get_queryset(self):
        # user = User.objects.get(username=self.request.user)
        return Post.objects.filter(
            is_approve=True,
            is_deleted=False
        ).order_by('-created_date')

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['notifications'], context['unread_count'] = recieve(self.request.user)
        return context


class CustomLoginView(FormView):
    form_class = LoginForm
    template_name = 'registration/login.html'
    success_url = 'post_list'

    def form_valid(self, form):
        user = authenticate(
            username=form.data['username'],
            password=form.data['password'])
        if user is not None:
            if user.is_active:
                login(self.request, user)
                return super().form_valid(form)
        else:
            messages.error(self.request, 'username or password not correct')
            return HttpResponseRedirect(self.get_success_url())


class EditorSignUpView(CreateView):
    model = User
    form_class = EditorSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Editor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


class ChiefSignUpView(CreateView):
    model = User
    form_class = ChiefSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Moderator'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('post_list')


@method_decorator([login_required], name='dispatch')
class IndexView(CreateView):
    """
    Create new blog
    """
    model = Post
    fields = ('title', 'text', )
    template_name = 'blog/add_post_form.html'
    success_url = 'post_list'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.owner = self.request.user
        post.save()
        return redirect('post_list')


@method_decorator([login_required], name='dispatch')
class PostListView(ListView):
    '''
    Show loggedIn user's post
    '''
    ordering = ('published_date',)
    context_object_name = 'post_list'
    template_name = 'blog/post_list.html'
    paginate_by = 10

    def get_queryset(self):
        # user = User.objects.get(username=self.request.user)
        return Post.objects.filter(
            owner_id=self.request.user,
            is_deleted=False
        )

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['users'] = False
        context['notifications'], context['unread_count'] = recieve(self.request.user)
        check = User.objects.filter(
            username=self.request.user,
            is_chief=True
        )
        if check:
            context['users'] = True
        return context


# @method_decorator([login_required], name='dispatch')
class PostDetailView(FormMixin, DetailView):
    model = Post
    form_class = CommentForm
    template_name = 'blog/post_detail.html'

    def get_success_url(self):
        return reverse_lazy('post_detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        comments = Comment.objects.filter(blog_id=self.get_object().id).order_by('-comment_datetime')[:5]
        context['notifications'], context['unread_count'] = recieve(self.request.user)
        # provide the columns name in values_list
        context['comments'] = comments.values_list(
            'user_id__username', 'comment', 'id')
        context['reply'] = Reply.objects.filter(blog_id=self.object.pk)
        context['form'] = CommentForm(initial={'post': self.object})
        return context

    @method_decorator(login_required, name='dispatch')
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        # Here, we would record the user's interest using the message
        # passed in form.cleaned_data['message']
        comment = form.save(commit=False)
        comment.blog = self.get_object()
        comment.user = self.request.user
        form.save()
        return super(PostDetailView, self).form_valid(form)


@method_decorator([login_required], name='dispatch')
class PostUpdateView(UpdateView):
    template_name = 'blog/add_post_form.html'
    model = Post
    fields = ['title', 'text']
    success_url = '/post_list'

    def get_context_data(self, **kwargs):
        context = super(PostUpdateView, self).get_context_data(**kwargs)
        context['notifications'], context['unread_count'] = recieve(self.request.user)
        return context


@method_decorator([login_required, chief_required], name='dispatch')
class PostApprovalListView(ListView):
    '''
        View to list of all post that need to be approved.
    '''
    template_name = 'blog/post_approve_list.html'
    ordering = ('published_date',)
    context_object_name = 'postApprove'
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.filter(is_approve=False)

    def get_context_data(self, **kwargs):
        context = super(PostApprovalListView, self).get_context_data(**kwargs)
        context['notifications'], context['unread_count'] = recieve(self.request.user)
        return context


@method_decorator([login_required, chief_required], name='dispatch')
class PostApprovalView(UpdateView):
    '''
        View create a form to approve the blog by moderator.
    '''
    template_name = 'blog/post_approval.html'
    model = Post
    fields = ['is_approve']
    # success_url = reverse_lazy('post_approve_list')

    def get_success_url(self):
        try:
            post = Post.objects.get(id=self.object.pk)
            if post.is_approve:
                verb = "%s Approved" % post.title
            else:
                verb = "%s Not Approved" % post.title
        except ObjectDoesNotExist:
            pass
        send(
            sender=self.request.user,
            recipient=User.objects.get(id=self.object.owner_id),
            verb=verb,
            blog_id=post.id
        )
        return reverse_lazy('post_approve_list')

    def get_context_data(self, **kwargs):
        context = super(PostApprovalView, self).get_context_data(**kwargs)
        context['notifications'], context['unread_count'] = recieve(self.request.user)
        return context


@method_decorator([login_required, chief_required], name='dispatch')
class PostApprovedView(ListView):
    '''
        View to show the approved post by loged in moderator
    '''
    template_name = 'blog/post_approve_list.html'
    ordering = ('published_date',)
    context_object_name = 'postApprove'
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.filter(is_approve=True)

    def get_context_data(self, **kwargs):
        context = super(PostApprovedView, self).get_context_data(**kwargs)
        context['notifications'], context['unread_count'] = recieve(self.request.user)
        return context


@method_decorator([login_required], name='dispatch')
class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')


@method_decorator([login_required], name='dispatch')
class CommentReplyView(FormMixin, DetailView):
    model = Comment
    form_class = ReplyForm
    template_name = 'blog/comment_reply.html'
    context_object_name = 'comment'

    def get_success_url(self):
        return reverse_lazy('comment_reply', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        # print(self.pk)
        context = super(CommentReplyView, self).get_context_data(**kwargs)
        reply = Reply.objects.filter(which_comment_id=self.get_object().id).order_by('-reply_datetime')[:5]
        comment = Comment.objects.filter(id=self.get_object().id)
        context['post'] = comment.values_list(
            'blog_id__title', 'blog_id__id',)
        context['notifications'], context['unread_count'] = recieve(self.request.user)
        # provide the columns name in values_list
        context['reply'] = reply.values_list('user_id__username', 'reply')
        context['form'] = ReplyForm(initial={'post': self.object})
        return context

    @method_decorator(login_required, name='dispatch')
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        reply = form.save(commit=False)

blog/templates/blog/add_post_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="post-edit">
        {% if post.owner == user %}
            <h3>Edit Post</h3>
        {% elif not post.owner%}
            <h1>Title: </h1>
        {% endif %}
        <form method="POST" class="post-form">
            {% csrf_token %}
            {% for field in form %}
                {{ field.errors }}
                <!-- <div id="froala-editor"> -->
                <!-- </div> -->
                {{ field }}
                <br/>
            {% endfor %}
            <button type="submit" class="btn btn-primary" id="post-save" name="submit">Submit</button>
        </form>
    </div>
{% endblock %}

blog/templates/blog/comment_reply.html
{% extends 'base.html' %}
{% block content %}
    <article>
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto" id="post-detail">
                {% for p in post%}
                    <a class="title" href="{% url 'post_detail' pk=p.1%}">
                        <h1 class="title">Comments for the Post {{p.0|title}}</h1>
                    </a>
                {% endfor %}
                {{ comment.comment|safe }}
            </div>
          </div>
        </div>
    </article>
    <hr>
    <div class="comment">
        <h1 class="title">Responses</h1>
        <form method="POST" class="form-comment" id="form-comment" data-validate-username='{{ user.username|title }}'>
            {% csrf_token %}  
            <div class="block-streamText"">
                <div class="postArticle postArticle--short">
                    {{ form }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
  </div>
    <hr>
    <div class="show-comment" id="show-comment">
    </div>
    <div class="show-comment">
        {% for r in reply %}
          <div class="panel panel-default arrow left">
            <div class="panel-body">
              <div class="comment-user"><i class="fa fa-user"></i> {{ r.0|title }}
              </div>
              <div class="comment-post">
                <p>
                  <span>{{ r.1 }}</span>
                </p>
              </div>
            </div>
          </div>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/greeting.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
      <div class="row">
        <div class="col-lg-10 col-md-12 mx-auto">
          <div class="row row-bottom-padded-sm" data-animate-effect="fadeInLeft">
            <div class="col-md-12">
              <div class="about-desc">
                <h2 class="colorlib-heading">Thanks, I will reach you shortly!</h2>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
{% endblock %}

blog/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
    <p> Hello World</p>
{% endblock %}

blog/templates/blog/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  {% for message in messages %}  {{ message }}
      <div class="alert alert-success">
          <a class="close" href="#" data-dismiss="alert">×</a>
          {{ message }}
      </div>
  {% endfor %}
  {% if form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {% for error in form.non_field_errors %}
        <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
      {% endfor %}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endif %}
  <div class="row">
    <div class="col-lg-4 col-md-6 col-sm-8 col-12">
      <h2>Log in</h2>
      <form method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ form.username|as_crispy_field }}
        {{ form.password|as_crispy_field }}
        <button type="submit" class="btn btn-primary">Log in</button>
      </form>
    </div>
  </div>
{% endblock %}

blog/templates/blog/post_approval.html
{% extends 'base.html' %}

{% block content %}

    <article>
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto" id="post-detail">
              <h1 class="title">{{ post.title|title }}</h1>
              <p class="post-metaa"> Posted by <a class="author-name" href="{% url 'user_detail' pk=user.pk %}">{{ post.owner|title }}</a> on {{ post.published_date|date:'d-m-Y' }}{% if post.is_approve %} &#x2713; {% else %} &#10007; {% endif %} 
                {% if post.owner == user %}
                  <a id='edit-post' href="{% url 'post_update' pk=post.pk %}"><i class="fas fa-pencil-alt"></i></a>
                  <form action="{% url 'post_delete' post.pk %}" method="post">{% csrf_token %}
                    <button id="confirm-delete">
                      <i class="far fa-trash-alt"></i>
                    </button>
                  </form>
                {% endif %}
              </p>
              {{ post.text|safe }}
            </div>
          </div>
          <form action="{% url 'post_approve' post.pk %}" method="post">
            {% csrf_token %}
            {% if not post.is_approve %}
              <input hidden type="checkbox" name="is_approve" id="id_is_approve" checked>
              <button type="submit" class="btn btn-primary" id="post-save" name="submit">Approve</button>
              <!-- <button value="true" id="approve">Approve</button> -->
            {% else %}
              <input hidden type="checkbox" name="is_approve" id="id_is_approve" unchecked>
              <!-- <button value="false" id="approve">Unapprove</button> -->
              <button type="submit" class="btn btn-primary" id="post-save" name="submit">Unapprove</button>
            {% endif %}
           </form>
        </div>
      </article>

{% endblock %}

blog/templates/blog/post_approve_list.html
{% extends 'base.html' %}
{% block content %}
    {% if postApprove %}            
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                {% for post in postApprove %}
                  <div class="post-preview" id="post-detail">
                    <a href="{% url 'post_approve' pk=post.pk %}">
                      <h2 class="post-title">
                        {{ post.title|title }}
                      </h2>
                      <!-- <p class="post-subtitle">
                        {{ post.text|safe|truncatechars:56 }}
                      </p> -->
                    </a>
                    <p class="post-meta"> Posted by <a href="{% url 'user_detail' pk=user.pk %}">{{ post.owner|title }}</a> on {{ post.published_date|date:'d-m-Y' }}{% if post.is_approve %} &#x2713; {% else %} &#10007; {% endif %}</p>
                  </div>
                  <hr>
                {% endfor %}
            </div>
          </div>
        </div>
        <br/>
    {% else %}
        <p align="center">No blogs to approve.</p>
    {% endif %}
    </div>

     <!-- Pager -->
    <div class="clear">
        {% if is_paginated %}
            <div class="paginate" style="text-align: center;">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a class="btn" href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a class="btn" href="?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    </div> 

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
 <!--  <div class="icon-bar">
    <a><i class="fas fa-thumbs-up"></i></a>
    <a><i class="fas fa-thumbs-down"></i></a>    
  </div> -->

  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto" id="post-detail">
          <h1 class="title">{{ post.title|title }}</h1>
          <p class="post-metaa"> Posted by <a class="author-name" href="{% url 'user_detail' pk=post.owner_id %}">{{ post.owner|title }}</a> on {{ post.published_date|date:'d-m-Y' }}{% if post.is_approve %} &#x2713; {% else %} &#10007; {% endif %} 
            {% if post.owner == user %}
              <a id='edit-post' href="{% url 'post_update' pk=post.pk %}"><i class="fas fa-pencil-alt"></i></a>
              <form action="{% url 'post_delete' post.pk %}" method="post">{% csrf_token %}
                <button id="confirm-delete">
                  <i class="far fa-trash-alt"></i>
                </button>
              </form>
            {% endif %}
          </p>
          {{ post.text|safe }}
        </div>
      </div>
    </div>
  </article>
  <hr>

  <div class="comment">
    <h1 class="title">Comment</h1>
    <form method="POST" class="form-comment" id="form-comment" data-validate-url='/post/{{post.id}}' data-validate-username='{{ user.username|title }}' >
        {% csrf_token %}  
        <div class="block-streamText"">
            <div class="postArticle postArticle--short">
                {{ form }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
    <hr>
    <div class="show-comment" id="show-comment">
    </div>
    <div class="show-comment">
        {% for comment in comments %}
          <div class="panel panel-default arrow left">
            <div class="panel-body">
              <div class="comment-user"><i class="fa fa-user"></i> {{ comment.0|title }}
                <a class="text-right" href="{% url 'comment_reply' pk=comment.2 %}"><i class="fa fa-reply"></i>Reply</a>
              </div>
              <div class="comment-post">
                <p>
                  <span>{{ comment.1|truncatechars:56 }}</span>
                </p>
              </div>
              <!-- <p class="text-right"><a href="#" class="btn btn-default btn-sm"><i class="fa fa-reply"></i> reply</a></p> -->
            </div>
          </div>
        {% endfor %}
    </div>
    
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% block content %}
    {% if post_list %}
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
              {% for post in post_list %}
                  <div class="post-preview" id="post-detail">
                    <a href="{% url 'post_detail' pk=post.pk %}">
                      <h2 class="post-title">
                        {{ post.title|title }}
                      </h2>
                      <!-- <p class="post-subtitle">
                        {{ post.text|safe|truncatechars:56 }}
                      </p> -->
                    </a>
                    <p class="post-meta"> Posted by <a href="{% url 'user_detail' pk=user.pk %}">{{ post.owner|title }}</a> on {{ post.published_date|date:'d-m-Y' }}{% if post.is_approve %} &#x2713; {% else %} &#10007; {% endif %}</p>
                  </div>
                  <hr>
                {% endfor %}
            </div>
          </div>
        </div>
    {% else %}
        <p> You have no blogs </p>
    {% endif %}
    {% if is_paginated %}
        <!-- Pager -->
        <div class="clear">
            {% if is_paginated %}
                <div class="paginate" style="text-align: center;">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a class="btn" href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a class="btn" href="?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

blog/templates/blog/registration.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

blog/templates/blog/userdetail.html
<img src="{{ user_info.avatar.url }}">

{{user_info.intro}}

{{user_info.bio|safe}}


{{user.first_name}}
{{user.username}}